### PR TITLE
fix(plugin-vue): support external import URLs for monorepos

### LINKED ISSUE #397: add watchers to imports within vue files
### Related plugins

- [X] [plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue)

- [ ] [plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

### Description

The watcher should rebuild vue files when the file's imports are updated. Without this, the rollup build doesn't rebuild when you update .ts and .scss/sass files that are in your build. This was fixed in vuejs/rollup-plugin-vue

### Suggested solution

In plugin-vue/src/index.ts line 291, add this code snippet
if (query.src) {
    this.addWatchFile(filename);
}

### Alternative

_No response_

### Additional context

Original Issues: https://github.com/vuejs/rollup-plugin-vue/issues/396
Original Fixes: https://github.com/vuejs/rollup-plugin-vue/pull/385

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by Kolobok12309**
### Description

Currently vue-plugin ignore watcher and use default vite config for it (root without node_modules), it not worked for monorepo's. And hmr not worked for shared script/style with src like this, but worked for .vue (reason later)

```
// node_modules/shared/index.vue
<template>
  <div> foo</div>
</template>

<script src="./index.ts"></script>

// node_modules/shared/index.ts
export default defineComponent({
  ...
})
```

In contrast of this internal vite-esbuild plugin add imports to watcher (because of it `.vue` hmr worked, because it imports from ts/js)

fix #397 

### Additional context

By default `vite` doesn't support hmr for `node_modules`, we enable it by https://github.com/vitejs/vite/issues/8619#issuecomment-2606507049

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [PR Title Convention](https://github.com/vitejs/vite/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by edison1105** [comment]
LGTM

File: packages/plugin-vue/src/index.ts [hunk 1]
```diff
@@ -330,6 +330,9 @@ export default function vuePlugin(rawOptions: Options = {}): Plugin<Api> {
       // select corresponding block for sub-part virtual modules
       if (query.vue) {
         if (query.src) {
+          if (options.value.devServer?.watcher) {
+            options.value.devServer.watcher.add(filename)
+          }
```
Comment (bluwy) [inline packages/plugin-vue/src/index.ts:335]: I think it should use this.addWatchFile instead, so it also works with Rollup build watch mode.

**Review by bluwy — APPROVED** [review]
